/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UsuarioLoginDialog.java
 *
 * Created on 21-abr-2010, 13:29:06
 */
package es.cvjpy.seguridad;

import es.cvjpy.GuiPro;
import es.cvjpy.PrincipalSeguroPro;
import es.cvjpy.PrincipalUIPro;
import es.cvjpy.util.ModeloGuiPro;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author CarlosVJ
 */
public class LoginDialog extends javax.swing.JDialog implements GuiPro {

    public LoginDialog() {
        this(new JFrame(), true);
    }

    /**
     * Creates new form UsuarioLoginDialog
     *
     * @param parent
     * @param modal
     */
    public LoginDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        centrar();
    }

    private void centrar() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel2 = new javax.swing.JPanel();
        campousuario = new javax.swing.JTextField();
        campoclave = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        versionPanel1 = new es.cvjpy.aplicacion.VersionPanel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        campousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campousuarioActionPerformed(evt);
            }
        });
        campousuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campousuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campousuarioFocusLost(evt);
            }
        });

        campoclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoclaveActionPerformed(evt);
            }
        });
        campoclave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoclaveFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoclaveFocusLost(evt);
            }
        });

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("seguridadlit"); // NOI18N
        jButton1.setText(bundle.getString("Aceptar")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText(bundle.getString("Usuario")); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText(bundle.getString("Clave")); // NOI18N

        resultado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        resultado.setForeground(new java.awt.Color(255, 0, 0));
        resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(campoclave, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campousuario, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultado, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${datos.versionAlfa}"), versionPanel1, org.jdesktop.beansbinding.BeanProperty.create("datos"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(versionPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(versionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

      try {
          comprobar();
      } catch (Exception ex) {
          Logger.getLogger(LoginDialog.class.getName()).log(Level.SEVERE, null, ex);
      }
      this.jButton1.transferFocus();

  }//GEN-LAST:event_jButton1ActionPerformed

  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

      this.fin();

  }//GEN-LAST:event_formWindowClosing

  private void campousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campousuarioActionPerformed
      this.campousuario.transferFocus();
  }//GEN-LAST:event_campousuarioActionPerformed

  private void campoclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoclaveActionPerformed
      this.campoclave.transferFocus();
      try {
          comprobar();
      } catch (Exception ex) {
          Logger.getLogger(LoginDialog.class.getName()).log(Level.SEVERE, null, ex);
      }
  }//GEN-LAST:event_campoclaveActionPerformed

  private void campousuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campousuarioFocusGained
      this.campoclave.setText("");
      this.campousuario.setSelectionStart(0);
      this.campousuario.setSelectionEnd(999);
  }//GEN-LAST:event_campousuarioFocusGained

  private void campoclaveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoclaveFocusGained
      this.campoclave.setSelectionStart(0);
      this.campoclave.setSelectionEnd(999);
  }//GEN-LAST:event_campoclaveFocusGained

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                comprobar();
            } catch (Exception ex) {
                Logger.getLogger(LoginDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void campousuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campousuarioFocusLost

        campousuario.setSelectionEnd(0);

    }//GEN-LAST:event_campousuarioFocusLost

    private void campoclaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoclaveFocusLost
        campoclave.setSelectionEnd(0);
    }//GEN-LAST:event_campoclaveFocusLost
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField campoclave;
    private javax.swing.JTextField campousuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel resultado;
    private es.cvjpy.aplicacion.VersionPanel versionPanel1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private final ModeloGuiPro auxiliar = new ModeloGuiPro(this);
    private UsuarioLoginCli datos;
    public static final String PROP_DATOS = "datos";

    public UsuarioLoginCli getDatos() {
        return datos;
    }

    public void setDatos(UsuarioLoginCli datos) {
        UsuarioLoginCli oldDatos = this.datos;
        this.datos = datos;
        firePropertyChange(PROP_DATOS, oldDatos, datos);
    }
    private int van = 0;

    private void comprobar() throws Exception {
        boolean ret = getDatos().comprobar(campousuario.getText().trim(), campoclave.getPassword());
        if (ret) {
            van = 0;
            setVisible(false);
            this.resultado.setText("");
            PrincipalSeguroPro padre = (PrincipalSeguroPro) auxiliar.getPadre();
            padre.setUsuario(getDatos().getUsuario());
            padre.usuarioCambiado();           
        } else {
            van++;
            if (van > 3) {
                this.fin();
            } else {
                resultado.setText(ResourceBundle.getBundle("seguridadlit").getString("Identificacion_no_es_valida"));
            }
        }
    }

    private PrincipalSeguroPro getPapaSeguro() {
        PrincipalSeguroPro ret = (PrincipalSeguroPro) auxiliar.getPadre();
        return ret;
    }
    @Override
    public void fin() {
        van = 0;
        this.setVisible(false);
    }
    private String antId;

    @Override
    public void inicio(PrincipalUIPro padre) {
        auxiliar.inicio(padre);
        van = 0;

        UsuarioLoginCli progs = new UsuarioLoginCli();
        progs.setPrincipalPro(padre.getServidor());
        progs.setUsuario(getPapaSeguro().getUsuario());
        setDatos(progs);
        try {
            antId = progs.getUsuarioId().trim();
        } catch (Exception ex) {
            Logger.getLogger(LoginDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        campousuario.setText(antId);

        setVisible(true);
        campousuario.requestFocus();

    }

    @Override
    public boolean puedosalir() {
        return true;
    }

    @Override
    public boolean isIniciado() {
        return auxiliar.isIniciado();
    }

    @Override
    public void rellama() {
        setVisible(true);
    }
}
